name: Podspec Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  podspec-lint:
    name: Validate FluidAudio podspec
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install CocoaPods
        run: sudo gem install cocoapods --no-document

      - name: Print tool versions
        run: |
          ruby --version
          pod --version

      - name: Lint podspec against working tree
        run: pod lib lint FluidAudio.podspec --allow-warnings
